NIFTY_COMPANIES = [
    "360 ONE WAM Ltd.",
    "3M India Ltd.",
    "ABB India Ltd.",
    "ACC Ltd.",
    "ACME Solar Holdings Ltd.",
    "AIA Engineering Ltd.",
    "APL Apollo Tubes Ltd.",
    "AU Small Finance Bank Ltd.",
    "AWL Agri Business Ltd.",
    "Aadhar Housing Finance Ltd.",
    "Aarti Industries Ltd.",
    "Aavas Financiers Ltd.",
    "Abbott India Ltd.",
    "Action Construction Equipment Ltd.",
    "Adani Energy Solutions Ltd.",
    "Adani Enterprises Ltd.",
    "Adani Green Energy Ltd.",
    "Adani Ports and Special Economic Zone Ltd.",
    "Adani Power Ltd.",
    "Adani Total Gas Ltd.",
    "Aditya Birla Capital Ltd.",
    "Aditya Birla Fashion and Retail Ltd.",
    "Aditya Birla Lifestyle Brands Ltd.",
    "Aditya Birla Real Estate Ltd.",
    "Aditya Birla Sun Life AMC Ltd.",
    "Aegis Logistics Ltd.",
    "Aegis Vopak Terminals Ltd.",
    "Afcons Infrastructure Ltd.",
    "Affle 3i Ltd.",
    "Ajanta Pharmaceuticals Ltd.",
    "Akums Drugs and Pharmaceuticals Ltd.",
    "Akzo Nobel India Ltd.",
    "Alembic Pharmaceuticals Ltd.",
    "Alkem Laboratories Ltd.",
    "Alkyl Amines Chemicals Ltd.",
    "Alok Industries Ltd.",
    "Amara Raja Energy & Mobility Ltd.",
    "Amber Enterprises India Ltd.",
    "Ambuja Cements Ltd.",
    "Anand Rathi Wealth Ltd.",
    "Anant Raj Ltd.",
    "Angel One Ltd.",
    "Apar Industries Ltd.",
    "Apollo Hospitals Enterprise Ltd.",
    "Apollo Tyres Ltd.",
    "Aptus Value Housing Finance India Ltd.",
    "Asahi India Glass Ltd.",
    "Ashok Leyland Ltd.",
    "Asian Paints Ltd.",
    "Aster DM Healthcare Ltd.",
    "AstraZenca Pharma India Ltd.",
    "Astral Ltd.",
    "Ather Energy Ltd.",
    "Atul Ltd.",
    "Aurobindo Pharma Ltd.",
    "Authum Investment & Infrastructure Ltd.",
    "Avenue Supermarts Ltd.",
    "Axis Bank Ltd.",
    "BASF India Ltd.",
    "BEML Ltd.",
    "BLS International Services Ltd.",
    "BSE Ltd.",
    "Bajaj Auto Ltd.",
    "Bajaj Finance Ltd.",
    "Bajaj Finserv Ltd.",
    "Bajaj Holdings & Investment Ltd.",
    "Bajaj Housing Finance Ltd.",
    "Balkrishna Industries Ltd.",
    "Balrampur Chini Mills Ltd.",
    "Bandhan Bank Ltd.",
    "Bank of Baroda",
    "Bank of India",
    "Bank of Maharashtra",
    "Bata India Ltd.",
    "Bayer Cropscience Ltd.",
    "Berger Paints India Ltd.",
    "Bharat Dynamics Ltd.",
    "Bharat Electronics Ltd.",
    "Bharat Forge Ltd.",
    "Bharat Heavy Electricals Ltd.",
    "Bharat Petroleum Corporation Ltd.",
    "Bharti Airtel Ltd.",
    "Bharti Hexacom Ltd.",
    "Bikaji Foods International Ltd.",
    "Biocon Ltd.",
    "Birlasoft Ltd.",
    "Blue Dart Express Ltd.",
    "Blue Jet Healthcare Ltd.",
    "Blue Star Ltd.",
    "Bombay Burmah Trading Corporation Ltd.",
    "Bosch Ltd.",
    "Brainbees Solutions Ltd.",
    "Brigade Enterprises Ltd.",
    "Britannia Industries Ltd.",
    "C.E. Info Systems Ltd.",
    "CCL Products (I) Ltd.",
    "CESC Ltd.",
    "CG Power and Industrial Solutions Ltd.",
    "CRISIL Ltd.",
    "Campus Activewear Ltd.",
    "Can Fin Homes Ltd.",
    "Canara Bank",
    "Caplin Point Laboratories Ltd.",
    "Capri Global Capital Ltd.",
    "Carborundum Universal Ltd.",
    "Castrol India Ltd.",
    "Ceat Ltd.",
    "Central Bank of India",
    "Central Depository Services (India) Ltd.",
    "Century Plyboards (India) Ltd.",
    "Cera Sanitaryware Ltd",
    "Chalet Hotels Ltd.",
    "Chambal Fertilizers & Chemicals Ltd.",
    "Chennai Petroleum Corporation Ltd.",
    "Choice International Ltd.",
    "Cholamandalam Financial Holdings Ltd.",
    "Cholamandalam Investment and Finance Company Ltd.",
    "Cipla Ltd.",
    "City Union Bank Ltd.",
    "Clean Science and Technology Ltd.",
    "Coal India Ltd.",
    "Cochin Shipyard Ltd.",
    "Coforge Ltd.",
    "Cohance Lifesciences Ltd.",
    "Colgate Palmolive (India) Ltd.",
    "Computer Age Management Services Ltd.",
    "Concord Biotech Ltd.",
    "Container Corporation of India Ltd.",
    "Coromandel International Ltd.",
    "Craftsman Automation Ltd.",
    "CreditAccess Grameen Ltd.",
    "Crompton Greaves Consumer Electricals Ltd.",
    "Cummins India Ltd.",
    "Cyient Ltd.",
    "DCM Shriram Ltd.",
    "DLF Ltd.",
    "DOMS Industries Ltd.",
    "Dabur India Ltd.",
    "Dalmia Bharat Ltd.",
    "Data Patterns (India) Ltd.",
    "Deepak Fertilisers & Petrochemicals Corp. Ltd.",
    "Deepak Nitrite Ltd.",
    "Delhivery Ltd.",
    "Devyani International Ltd.",
    "Divi's Laboratories Ltd.",
    "Dixon Technologies (India) Ltd.",
    "Dr. Agarwal's Health Care Ltd.",
    "Dr. Lal Path Labs Ltd.",
    "Dr. Reddy's Laboratories Ltd.",
    "E.I.D. Parry (India) Ltd.",
    "EIH Ltd.",
    "Eicher Motors Ltd.",
    "Elecon Engineering Co. Ltd.",
    "Elgi Equipments Ltd.",
    "Emami Ltd.",
    "Emcure Pharmaceuticals Ltd.",
    "Endurance Technologies Ltd.",
    "Engineers India Ltd.",
    "Eris Lifesciences Ltd.",
    "Escorts Kubota Ltd.",
    "Eternal Ltd.",
    "Exide Industries Ltd.",
    "FSN E-Commerce Ventures Ltd.",
    "Federal Bank Ltd.",
    "Fertilisers and Chemicals Travancore Ltd.",
    "Finolex Cables Ltd.",
    "Finolex Industries Ltd.",
    "Firstsource Solutions Ltd.",
    "Five-Star Business Finance Ltd.",
    "Force Motors Ltd.",
    "Fortis Healthcare Ltd.",
    "GAIL (India) Ltd.",
    "GE Vernova T&D India Ltd.",
    "GMR Airports Ltd.",
    "Garden Reach Shipbuilders & Engineers Ltd.",
    "General Insurance Corporation of India",
    "Gillette India Ltd.",
    "Gland Pharma Ltd.",
    "Glaxosmithkline Pharmaceuticals Ltd.",
    "Glenmark Pharmaceuticals Ltd.",
    "Global Health Ltd.",
    "Go Digit General Insurance Ltd.",
    "Godawari Power & Ispat Ltd.",
    "Godfrey Phillips India Ltd.",
    "Godrej Agrovet Ltd.",
    "Godrej Consumer Products Ltd.",
    "Godrej Industries Ltd.",
    "Godrej Properties Ltd.",
    "Granules India Ltd.",
    "Graphite India Ltd.",
    "Grasim Industries Ltd.",
    "Gravita India Ltd.",
    "Great Eastern Shipping Co. Ltd.",
    "Gujarat Fluorochemicals Ltd.",
    "Gujarat Gas Ltd.",
    "Gujarat Mineral Development Corporation Ltd.",
    "Gujarat State Petronet Ltd.",
    "H.E.G. Ltd.",
    "HBL Engineering Ltd.",
    "HCL Technologies Ltd.",
    "HDFC Asset Management Company Ltd.",
    "HDFC Bank Ltd.",
    "HDFC Life Insurance Company Ltd.",
    "HFCL Ltd.",
    "Happiest Minds Technologies Ltd.",
    "Havells India Ltd.",
    "Hero MotoCorp Ltd.",
    "Hexaware Technologies Ltd.",
    "Himadri Speciality Chemical Ltd.",
    "Hindalco Industries Ltd.",
    "Hindustan Aeronautics Ltd.",
    "Hindustan Copper Ltd.",
    "Hindustan Petroleum Corporation Ltd.",
    "Hindustan Unilever Ltd.",
    "Hindustan Zinc Ltd.",
    "Hitachi Energy India Ltd.",
    "Home First Finance Company India Ltd.",
    "Honasa Consumer Ltd.",
    "Honeywell Automation India Ltd.",
    "Housing & Urban Development Corporation Ltd.",
    "Hyundai Motor India Ltd.",
    "ICICI Bank Ltd.",
    "ICICI Lombard General Insurance Company Ltd.",
    "ICICI Prudential Life Insurance Company Ltd.",
    "IDBI Bank Ltd.",
    "IDFC First Bank Ltd.",
    "IFCI Ltd.",
    "IIFL Finance Ltd.",
    "INOX India Ltd.",
    "IRB Infrastructure Developers Ltd.",
    "IRCON International Ltd.",
    "ITC Hotels Ltd.",
    "ITC Ltd.",
    "ITI Ltd.",
    "Indegene Ltd.",
    "India Cements Ltd.",
    "Indiamart Intermesh Ltd.",
    "Indian Bank",
    "Indian Energy Exchange Ltd.",
    "Indian Hotels Co. Ltd.",
    "Indian Oil Corporation Ltd.",
    "Indian Overseas Bank",
    "Indian Railway Catering And Tourism Corporation Ltd.",
    "Indian Railway Finance Corporation Ltd.",
    "Indian Renewable Energy Development Agency Ltd.",
    "Indraprastha Gas Ltd.",
    "Indus Towers Ltd.",
    "IndusInd Bank Ltd.",
    "Info Edge (India) Ltd.",
    "Infosys Ltd.",
    "Inox Wind Ltd.",
    "Intellect Design Arena Ltd.",
    "InterGlobe Aviation Ltd.",
    "International Gemmological Institute (India) Ltd.",
    "Inventurus Knowledge Solutions Ltd.",
    "Ipca Laboratories Ltd.",
    "J.B. Chemicals & Pharmaceuticals Ltd.",
    "J.K. Cement Ltd.",
    "JBM Auto Ltd.",
    "JK Tyre & Industries Ltd.",
    "JM Financial Ltd.",
    "JSW Cement Ltd.",
    "JSW Energy Ltd.",
    "JSW Infrastructure Ltd.",
    "JSW Steel Ltd.",
    "Jaiprakash Power Ventures Ltd.",
    "Jammu & Kashmir Bank Ltd.",
    "Jindal Saw Ltd.",
    "Jindal Stainless Ltd.",
    "Jindal Steel Ltd.",
    "Jio Financial Services Ltd.",
    "Jubilant Foodworks Ltd.",
    "Jubilant Ingrevia Ltd.",
    "Jubilant Pharmova Ltd.",
    "Jupiter Wagons Ltd.",
    "Jyothy Labs Ltd.",
    "Jyoti CNC Automation Ltd.",
    "K.P.R. Mill Ltd.",
    "KEI Industries Ltd.",
    "KPIT Technologies Ltd.",
    "KSB Ltd.",
    "Kajaria Ceramics Ltd.",
    "Kalpataru Projects International Ltd.",
    "Kalyan Jewellers India Ltd.",
    "Karur Vysya Bank Ltd.",
    "Kaynes Technology India Ltd.",
    "Kec International Ltd.",
    "Kfin Technologies Ltd.",
    "Kirloskar Brothers Ltd.",
    "Kirloskar Oil Eng Ltd.",
    "Kotak Mahindra Bank Ltd.",
    "Krishna Institute of Medical Sciences Ltd.",
    "Kwality Wall's (India) Ltd.",
    "L&T Finance Ltd.",
    "L&T Technology Services Ltd.",
    "LIC Housing Finance Ltd.",
    "LT Foods Ltd.",
    "LTIMindtree Ltd.",
    "Larsen & Toubro Ltd.",
    "Latent View Analytics Ltd.",
    "Laurus Labs Ltd.",
    "Leela Palaces Hotels & Resorts Ltd.",
    "Lemon Tree Hotels Ltd.",
    "Life Insurance Corporation of India",
    "Linde India Ltd.",
    "Lloyds Metals And Energy Ltd.",
    "Lodha Developers Ltd.",
    "Lupin Ltd.",
    "MMTC Ltd.",
    "MRF Ltd.",
    "Mahanagar Gas Ltd.",
    "Maharashtra Scooters Ltd.",
    "Maharashtra Seamless Ltd.",
    "Mahindra & Mahindra Financial Services Ltd.",
    "Mahindra & Mahindra Ltd.",
    "Manappuram Finance Ltd.",
    "Mangalore Refinery & Petrochemicals Ltd.",
    "Mankind Pharma Ltd.",
    "Marico Ltd.",
    "Maruti Suzuki India Ltd.",
    "Max Financial Services Ltd.",
    "Max Healthcare Institute Ltd.",
    "Mazagoan Dock Shipbuilders Ltd.",
    "Metropolis Healthcare Ltd.",
    "Minda Corporation Ltd.",
    "Motherson Sumi Wiring India Ltd.",
    "Motilal Oswal Financial Services Ltd.",
    "MphasiS Ltd.",
    "Multi Commodity Exchange of India Ltd.",
    "Muthoot Finance Ltd.",
    "NATCO Pharma Ltd.",
    "NBCC (India) Ltd.",
    "NCC Ltd.",
    "NHPC Ltd.",
    "NLC India Ltd.",
    "NMDC Ltd.",
    "NMDC Steel Ltd.",
    "NTPC Green Energy Ltd.",
    "NTPC Ltd.",
    "Narayana Hrudayalaya Ltd.",
    "National Aluminium Co. Ltd.",
    "Nava Ltd.",
    "Navin Fluorine International Ltd.",
    "Nestle India Ltd.",
    "Netweb Technologies India Ltd.",
    "Neuland Laboratories Ltd.",
    "Newgen Software Technologies Ltd.",
    "Nippon Life India Asset Management Ltd.",
    "Niva Bupa Health Insurance Company Ltd.",
    "Nuvama Wealth Management Ltd.",
    "Nuvoco Vistas Corporation Ltd.",
    "Oberoi Realty Ltd.",
    "Oil & Natural Gas Corporation Ltd.",
    "Oil India Ltd.",
    "Ola Electric Mobility Ltd.",
    "Olectra Greentech Ltd.",
    "One 97 Communications Ltd.",
    "Onesource Specialty Pharma Ltd.",
    "Oracle Financial Services Software Ltd.",
    "PB Fintech Ltd.",
    "PCBL Chemical Ltd.",
    "PG Electroplast Ltd.",
    "PI Industries Ltd.",
    "PNB Housing Finance Ltd.",
    "PTC Industries Ltd.",
    "PVR INOX Ltd.",
    "Page Industries Ltd.",
    "Patanjali Foods Ltd.",
    "Persistent Systems Ltd.",
    "Petronet LNG Ltd.",
    "Pfizer Ltd.",
    "Phoenix Mills Ltd.",
    "Pidilite Industries Ltd.",
    "Piramal Pharma Ltd.",
    "Poly Medicure Ltd.",
    "Polycab India Ltd.",
    "Poonawalla Fincorp Ltd.",
    "Power Finance Corporation Ltd.",
    "Power Grid Corporation of India Ltd.",
    "Praj Industries Ltd.",
    "Premier Energies Ltd.",
    "Prestige Estates Projects Ltd.",
    "Procter & Gamble Hygiene & Health Care Ltd.",
    "Punjab National Bank",
    "R R Kabel Ltd.",
    "RBL Bank Ltd.",
    "REC Ltd.",
    "RHI MAGNESITA INDIA LTD.",
    "RITES Ltd.",
    "Radico Khaitan Ltd",
    "Rail Vikas Nigam Ltd.",
    "Railtel Corporation Of India Ltd.",
    "Rainbow Childrens Medicare Ltd.",
    "Ramkrishna Forgings Ltd.",
    "Rashtriya Chemicals & Fertilizers Ltd.",
    "Redington Ltd.",
    "Reliance Industries Ltd.",
    "Reliance Infrastructure Ltd.",
    "Reliance Power Ltd.",
    "SBFC Finance Ltd.",
    "SBI Cards and Payment Services Ltd.",
    "SBI Life Insurance Company Ltd.",
    "SJVN Ltd.",
    "SRF Ltd.",
    "Sagility Ltd.",
    "Sai Life Sciences Ltd.",
    "Sammaan Capital Ltd.",
    "Samvardhana Motherson International Ltd.",
    "Sapphire Foods India Ltd.",
    "Sarda Energy and Minerals Ltd.",
    "Saregama India Ltd",
    "Schaeffler India Ltd.",
    "Schneider Electric Infrastructure Ltd.",
    "Shipping Corporation of India Ltd.",
    "Shree Cement Ltd.",
    "Shriram Finance Ltd.",
    "Shyam Metalics and Energy Ltd.",
    "Siemens Energy India Ltd.",
    "Siemens Ltd.",
    "Signatureglobal (India) Ltd.",
    "Sobha Ltd.",
    "Solar Industries India Ltd.",
    "Sona BLW Precision Forgings Ltd.",
    "Sonata Software Ltd.",
    "Star Health and Allied Insurance Company Ltd.",
    "State Bank of India",
    "Steel Authority of India Ltd.",
    "Sumitomo Chemical India Ltd.",
    "Sun Pharmaceutical Industries Ltd.",
    "Sun TV Network Ltd.",
    "Sundaram Finance Ltd.",
    "Sundram Fasteners Ltd.",
    "Supreme Industries Ltd.",
    "Suzlon Energy Ltd.",
    "Swan Corp Ltd.",
    "Swiggy Ltd.",
    "Syngene International Ltd.",
    "Syrma SGS Technology Ltd.",
    "TBO Tek Ltd.",
    "TVS Motor Company Ltd.",
    "Tata Chemicals Ltd.",
    "Tata Communications Ltd.",
    "Tata Consultancy Services Ltd.",
    "Tata Consumer Products Ltd.",
    "Tata Elxsi Ltd.",
    "Tata Investment Corporation Ltd.",
    "Tata Motors Passenger Vehicles Ltd.",
    "Tata Power Co. Ltd.",
    "Tata Steel Ltd.",
    "Tata Technologies Ltd.",
    "Tata Teleservices (Maharashtra) Ltd.",
    "Tech Mahindra Ltd.",
    "Techno Electric & Engineering Company Ltd.",
    "Tejas Networks Ltd.",
    "The New India Assurance Company Ltd.",
    "The Ramco Cements Ltd.",
    "Thermax Ltd.",
    "Timken India Ltd.",
    "Titagarh Rail Systems Ltd.",
    "Titan Company Ltd.",
    "Torrent Pharmaceuticals Ltd.",
    "Torrent Power Ltd.",
    "Transformers And Rectifiers (India) Ltd.",
    "Trent Ltd.",
    "Trident Ltd.",
    "Triveni Engineering & Industries Ltd.",
    "Triveni Turbine Ltd.",
    "Tube Investments of India Ltd.",
    "UCO Bank",
    "UNO Minda Ltd.",
    "UPL Ltd.",
    "UTI Asset Management Company Ltd.",
    "UltraTech Cement Ltd.",
    "Union Bank of India",
    "United Breweries Ltd.",
    "United Spirits Ltd.",
    "Usha Martin Ltd.",
    "V-Guard Industries Ltd.",
    "Valor Estate Ltd.",
    "Vardhman Textiles Ltd.",
    "Varun Beverages Ltd.",
    "Vedant Fashions Ltd.",
    "Vedanta Ltd.",
    "Ventive Hospitality Ltd.",
    "Vijaya Diagnostic Centre Ltd.",
    "Vishal Mega Mart Ltd.",
    "Vodafone Idea Ltd.",
    "Voltas Ltd.",
    "Waaree Energies Ltd.",
    "Welspun Corp Ltd.",
    "Welspun Living Ltd.",
    "Whirlpool of India Ltd.",
    "Wipro Ltd.",
    "Wockhardt Ltd.",
    "Yes Bank Ltd.",
    "ZF Commercial Vehicle Control Systems India Ltd.",
    "Zee Entertainment Enterprises Ltd.",
    "Zen Technologies Ltd.",
    "Zensar Technolgies Ltd.",
    "Zydus Lifesciences Ltd.",
    "eClerx Services Ltd."
]